name: Deploy Proyecto DevOps

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "proyecto-devops" ]; then
              git clone https://github.com/mcoradog5-ctrl/proyecto-devops.git
            fi
            cd proyecto-devops
            git pull origin main
            # Apaga los contenedores viejos y levanta la nueva arquitectura
            docker compose down || true
            docker compose up -d --build